version: '3.8'

name: mu2mi

services:
    # web-migration:
    #     build:
    #         context: .
    #         dockerfile: migration.Dockerfile
    #         target: migration
    #     container_name: web-migration
    #     restart: on-failure
    #     environment:
    #         - DATABASE_URL=${DATABASE_URL}
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
    #     network_mode: host

    # bucket-creation:
    #     build:
    #         context: .
    #         dockerfile: bucket-creation.Dockerfile
    #         target: bucket-creation
    #     container_name: bucket-creation
    #     restart: on-failure
    #     environment:
    #         - S3_ENDPOINT=${S3_ENDPOINT}
    #         - S3_PORT=${S3_PORT}
    #         - S3_USE_SSL=${S3_USE_SSL}
    #         - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    #         - S3_SECRET_KEY=${S3_SECRET_KEY}
    #         - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    #         - S3_BUCKET_REGION=${S3_BUCKET_REGION}
    #     depends_on:
    #         minio:
    #             condition: service_healthy
    #     network_mode: host

    postgres:
        image: postgres:16.1-alpine3.19
        container_name: postgres
        restart: unless-stopped
        environment:
            - PGUSER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 1s
            timeout: 5s
            retries: 10

    redis:
        image: redis:7.2.4-alpine
        container_name: redis
        restart: unless-stopped
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - redis-data:/data
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 1s
            timeout: 5s
            retries: 10

    minio:
        image: quay.io/minio/minio:RELEASE.2024-01-18T22-51-28Z
        container_name: minio
        restart: unless-stopped
        command: server /data --console-address ":${S3_CONSOLE_PORT}"
        environment:
            - MINIO_ROOT_USER=${S3_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
        ports:
            - ${INTERNAL_S3_PORT}:${INTERNAL_S3_PORT}
            - ${S3_CONSOLE_PORT}:${S3_CONSOLE_PORT}
        volumes:
            - minio_data:/data
        healthcheck:
            test: ['CMD', 'mc', 'ready', 'local']
            interval: 1s
            timeout: 5s
            retries: 10

    bucket-init:
        image: minio/mc
        container_name: bucket-init
        restart: no
        entrypoint: /bin/sh -c "/usr/bin/mc config host add minio http://${INTERNAL_S3_ENDPOINT}:${INTERNAL_S3_PORT} ${S3_ACCESS_KEY} ${S3_SECRET_KEY} && /usr/bin/mc mb minio/${S3_BUCKET_NAME} && /usr/bin/mc anonymous set public minio/${S3_BUCKET_NAME} && exit 0"
        environment:
            - INTERNAL_S3_ENDPOINT=${INTERNAL_S3_ENDPOINT}
            - INTERNAL_S3_PORT=${INTERNAL_S3_PORT}
            - S3_ACCESS_KEY=${S3_ACCESS_KEY}
            - S3_SECRET_KEY=${S3_SECRET_KEY}
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
        depends_on:
            minio:
                condition: service_healthy

    jaeger-all-in-one:
        image: jaegertracing/all-in-one:1
        restart: always
        ports:
            - '16686:16686'
            - '14268'
            - '14250'

    zipkin-all-in-one:
        image: openzipkin/zipkin:3
        restart: always
        ports:
            - '9411:9411'

    otel-collector:
        image: otel/opentelemetry-collector:0.67.0
        restart: always
        command: ['--config=/etc/otel-collector-config.yaml']
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '1888:1888' # pprof extension
            - '8888:8888' # Prometheus metrics exposed by the collector
            - '8889:8889' # Prometheus exporter metrics
            - '13133:13133' # health_check extension
            - '4317:4317' # OTLP gRPC receiver
            - '4318:4318' # OTLP HTTP receiver
            - '55679:55679' # zpages extension
        depends_on:
            - jaeger-all-in-one
            - zipkin-all-in-one

    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.50.1
        restart: always
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        ports:
            - '9090:9090'

volumes:
    postgres-data:
        driver: local
    redis-data:
        driver: local
    minio_data:
        driver: local
    prometheus-data:
        driver: local
